### ISSUE TITLE
运行"tcbf plot-syn-pair"遇到了问题

### ISSUE THREAD

**Issue by kuangzhuoran** [TcbfGroup/Tcbf#1]
您好！谢谢提供这个工具，运行速度超级快

第一个问题是
"FileNotFoundError: [Errno 2] No such file or directory: 'out/Step1/sppA.bound.bed'"
大概是boundary的文件找不到？
我检查了一下发现是因为Step1中的是sppA.boundary.bed，所以手动改了名字改成了sppA.bound.bed

第二个问题是FileNotFoundError: [Errno 2] No such file or directory: 'out/Result/one_to_many/sppA.txt'
这个是因为输出的文件名字是叫 onetomany, 所以手动改了输出文件夹的名字

最后遇到的问题是
ValueError: Length mismatch: Expected axis has 0 elements, new values have 4 elements
这个我不知道该作何更改了= =

以下是完整的log:
Traceback (most recent call last):
  File "/home/kuangzhr17/miniconda3/bin/tcbf", line 4, in <module>
    __import__('pkg_resources').run_script('tcbf==1.0', 'tcbf')
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1572, in run_script
    exec(script_code, namespace, namespace)
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/tcbf-1.0-py3.9.egg/EGG-INFO/scripts/tcbf", line 173, in <module>
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/tcbf-1.0-py3.9.egg/EGG-INFO/scripts/tcbf", line 158, in plot_syn_pair
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/tcbf-1.0-py3.9.egg/tcbf/plot_tad_structure.py", line 424, in plot_synteny
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/tcbf-1.0-py3.9.egg/tcbf/plot_tad_structure.py", line 415, in plot_main
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/tcbf-1.0-py3.9.egg/tcbf/plot_tad_structure.py", line 337, in plot_boundary_pair
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/kuangzhr17/miniconda3/lib/python3.9/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 4 elements

**Comment by kuangzhuoran** [comment]
我的命令行是:
tcbf plot-syn-pair -o 4spp --reference sppA --chrom Chr1 --start 76510000 --end 80280000 --plot example.pdf

**Comment by TcbfGroup** [comment]
感谢您使用我们的软件，这个绘图中间文件名可能在之前改代码的时候忘了改了。我会在假期之后改一下代码。
对于最后的报错，你可以检查一下输入的基因组区域包含的TAD是否在tcbf的输出文件中其他物种有对应的TAD，如果该区域无保守的TAD,可能会有此错误。
如果还有其他问题且比较急，欢迎加我微信交流。微信号为 hexin19981001



---Original---
From: ***@***.***&gt;
Sent at: 2023年12月30日(Sat) PM3:49
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [TcbfGroup/Tcbf] 运行"tcbf plot-syn-pair"遇到了问题 (Issue #1)




 
我的命令行是:
 tcbf plot-syn-pair -o 4spp --reference sppA --chrom Chr1 --start 76510000 --end 80280000 --plot example.pdf

**Comment by kuangzhuoran** [comment]
您好! 谢谢你的回复，我又产生了几个疑问

一、Tcbf如何统计不同保守程度的边界
e.g. ‘被所有物种共享的边界’/‘被N个物种共享’/‘物种特有的边界’

我的想法是：
1.1 翻阅输出文件TAD_groups.tsv后，我发现如果某个Group中的边界对应了所有物种
比如下图，那这样的边界或者Group就是‘所有物种共享的’，N’个物种共享的边界‘同理。
![TAD_groups.tsv](https://github.com/TcbfGroup/Tcbf/assets/76553133/21d3b827-708a-4845-a1bc-43140bd1e386)
1.2 ‘物种特有的边界’则是Unassignd_TAD.tsv。

1.3 我的疑问是，有时候某物种在一个Group里面会有好多边界，也就是TAD_groups_count.tsv，有很多行的数字都大于1 (1.3.1)，这是否对应在画图的时候存在一个边界对应多个边界的情况 (1.3.3)，如下图。。一个边界对应多个边界的情况有何处理的方法吗
![1.3.1. 一个边界对应多个边界的情况](https://github.com/TcbfGroup/Tcbf/assets/76553133/fe68440d-bb38-4eca-8560-dbbf2dd0460e)
![1.3.2. 我认为的理想中的保守边界的情况](https://github.com/TcbfGroup/Tcbf/assets/76553133/d5dc069e-6d8f-4df7-a49e-0cb11461444c)
![1.3.3. 一个边界对应多个边界](https://github.com/TcbfGroup/Tcbf/assets/76553133/43d7cded-9584-468b-a924-b7b04190efe8)

**Comment by TcbfGroup** [comment]
1.1 你的想法是对的。
1.2 特异性的边界包括 Unassigned_TAD 和  TAD_groups_count.tsv中某个Group中所有成员来自同一个物种  如  2 0 0 0 这样的
1.3 这里软件会计算同源TAD边界数最多的一个区域进行绘制，比如说你对A物种1-10Mb的区域中10个TAD边界进行保守TAD边界计算，分别对应到了B物种的1-8Mb的8个边界和20-25Mb区域的6个边界，绘图则仅绘制1-8Mb的同源区域。

**Comment by kuangzhuoran** [comment]
谢谢你的回复！
对于  4  4  4  4 / 5  4  3  3 / 这样全都不是1的边界应该怎么处理比较合适呢
这表明每个物种都有多个TAD边界内都有相同的基因？
我想的是可能简单过滤掉这样的边界

**Comment by HeXinSysu** [comment]
这个取决于你的研究问题，如果想要得到多物种比较保守的TAD边界数量，就可以认为4个都是保守的边界。就像同源基因一样。

**Comment by TcbfGroup** [comment]
这个取决于你的研究问题，如果想要得到多物种比较保守的TAD边界数量，就可以认为4个都是保守的边界。就像同源基因一样。

**Comment by kuangzhuoran** [comment]
"对于 4 4 4 4 / 5 4 3 3 / 这样全都不是1的边界"
类似于
他们是同源基因，但是只不过不是同源单拷贝基因？

**Comment by dengyang111** [comment]
> 我的命令行是: tcbf plot-syn-pair -o 4spp --reference sppA --chrom Chr1 --start 76510000 --end 80280000 --plot example.pdf

您好，可以添加一下您的微信么，我有几个问题想请教一下。谢谢

**Comment by wangzhaohui-001** [comment]
你好，
不知道我理解的对不对，group结果中所有物种中均不为0的是保守边界，group结果中只要一个物种为1的为物种特异性边界。
是这样的话我的结果中，保守的特异性占比例很低！

<img width="1534" height="407" alt="Image" src="https://github.com/user-attachments/assets/44b97556-28e8-495e-9ae1-1d2add0b4227" />

<img width="1596" height="552" alt="Image" src="https://github.com/user-attachments/assets/2ac89eb1-aaad-4ee8-8859-2b97059a9bf9" />
